- microcosm_postgres/store.py
- microcosm_postgres/tests/example.py
- microcosm_postgres/tests/test_example.py
Allow searching and counting to use kwargs to filter queries.
This makes it easier to bind searches directly to generic query string arguments for various kinds of filtering.
> Support filtering by kwargs as a first-class operation.

- microcosm_postgres/diff.py
- microcosm_postgres/models.py
- microcosm_postgres/store.py
- microcosm_postgres/tests/test_example.py
Adds a new store operation that computes a delta between the before and after state of an instance.
Also fixes:
- an issue where `created_at` was not updated properly
- some non-realistic elements of existing update tests
> Support update_with_diff

- CHANGES.md
- microcosm_postgres/factories.py
This will ensure that the default connection to databases uses SSL.
The option is configurable.
In addition, we want to be able to verify the certificate from the client side,
providing a root CA available to the application.
> Enforce SSL connection to database, enable full certificate verification if desired

- microcosm_postgres/health.py
- add health check function that returns the current head version
Why?
Exposing the current head version to the health check will make it easy
to determine if the database is caught up on migrations.
> Add get_current_head health check

- .bumpversion.cfg
- microcosm_postgres/health.py
- setup.py
- add health check function that returns the current head version
Why?
Exposing the current head version to the health check will make it easy
> Add get_current_head health check (#43)

- microcosm_postgres/store.py
- microcosm_postgres/tests/test_company_store.py
Why?
The count call to the store should not have pagination factored in. This is typically done at the CRUDStoreAdaptor level in microcosm-flask (by just avoiding passing in limit/offset to the store's count function) but more accurately should be done in the store. Also makes it consistent with microcosm-sqlite
> Remove pagination out of filter

- microcosm_postgres/encryption/encryptor.py
- microcosm_postgres/encryption/factories.py
- microcosm_postgres/encryption/models.py
- microcosm_postgres/encryption/providers.py
- microcosm_postgres/tests/encryption/fixtures.py
- microcosm_postgres/tests/encryption/test_encryptor.py
- microcosm_postgres/tests/encryption/test_models.py
- microcosm_postgres/tests/test_serial_type.py
- setup.py
This PR adds an `extra` dependency on `aws-encryption-sdk` that knows how to encrypt
plaintext using KMS prior to writing anything to postgres.
There are three components at the moment:
1. An `EncryptedMixin` for the orm-mapped model. It includes encrypted binary data
and a list of master key ids used for encryption. The intent is that by persistin
the key ids that are actually used, we reduce the effort of re-keying old data
once key rotation has occurred. There will need to be future work here to manage
*conditional* encryption in multi-tenant cases; this may be best achieved by having
all encrypted data in a secondary table.
2. An `Encryptor` abstraction that delegates to `aws-encryption-sdk`. This abstraction
allows us to manage encryptor configuration using microcosm abstractions …
> Initial interface for application-layer encryption onto of microcosm-postgres.

- microcosm_postgres/models.py
- microcosm_postgres/tests/encryption/test_models.py
If models use `relationship`, `_members` will include child rows; doing so is
both unecessary (assuming a foreign key id) and potentially breaks some upsert
usages that operate over `_members`.
> Ignore nested models in entity identity

- microcosm_postgres/encryption/models.py
- microcosm_postgres/encryption/store.py
- microcosm_postgres/tests/encryption/fixtures/encrpytable.py
- microcosm_postgres/tests/encryption/fixtures/json_encrpytable.py
- microcosm_postgres/tests/encryption/test_models.py
sqlalchemy relationship should allows to easily update/delete encrypted_model in respond to changes in model. This should allow us to delete orphans rows and to easily update models. This is a sqlalchemy function, not psql.
See: https://docs.sqlalchemy.org/en/latest/orm/cascades.html
* We can support update using `cascade`
* Because the way that the foreign keys our describes models are built (see examples) the `delete cascade` won't work. For now, we can move this functionality to the store (It was already there in the example)
* Maybe in a future version we will change the foreign keys constraints and discard the store
> Encryption: Delete and Update examples

- microcosm_postgres/encryption/models.py
- microcosm_postgres/encryption/store.py
- microcosm_postgres/tests/encryption/fixtures/encryptable.py
- microcosm_postgres/tests/encryption/fixtures/json_encryptable.py
- microcosm_postgres/tests/encryption/fixtures/nullable_encryptable.py
- microcosm_postgres/tests/encryption/test_models.py
EncryptableStore.update is going to support seamlessly update:
The controller won't have to
* Change the encryption context key
* Reset encrypted value
* Set instance.plaintext to the updated one (The controller should still set it for the `create`), we should still need to find the right pattern here.
Also, we won't use `cascade` anymore that gave inconsistent results - per @sethisernhagen recommendation
>  Smart EncryptableStore.update

- microcosm_postgres/encryption/store.py
- microcosm_postgres/tests/encryption/test_models.py
This is an optimization to be able to fetch all IDs that have been
encrypted without needing to load up all of the encrypted data at the
same time.
> Add encrypted ID search

- .circleci/config.yml
- .globality/build.json
- microcosm_postgres/store.py
- microcosm_postgres/tests/test_company_store.py
Why? SqlAlchemy `delete` attemps to synchronize the session before the
commit. It does so by taking a middle ground between performance and
convenience, but it also exposes other strategies based on the use case.
This PR exposes those other strategies for other use cases that may
arise.
The default `evaluate` is nice, but the way the store is written
requires overwriting the built-in `_delete` method to gain access to the
other `sqlalchemy` session synch strategies. This matters because the
other strategies (no strategy and `fetch`) are more efficient and more
convenient respectively.
> Expose the synchronize session delete param.

- microcosm_postgres/metrics.py
- microcosm_postgres/store.py
- microcosm_postgres/tests/test_company_store.py
- microcosm_postgres/tests/test_metrics.py
- setup.py
Task: https://globality.atlassian.net/browse/GLOB-38849
This PR adds metrics to postgres-store layer. Operations we are capturing metrics on are: create, retrieve, update, update_with_diff, delete, count, search, search_first
> GLOB-38849: added metrics to postgres-store

- microcosm_postgres/operations.py
- microcosm_postgres/tests/test_serial_type.py
After analyzing some slow-running unit test runs across a few services,
it became apparent that this could be largely attributed to
creating/dropping the database in between each test case.
Namely, there is a large cost attributed with evaluating each
table/column from scratch between tests. Locally, this could table up to
half a second(!). On some repos with 500+ tests, this adds up.
This change should reduce the cost of resetting the database (after the
initial run) milliseconds.
Tested this out on a number of repos, with substantial differences:
* 873 tests: 490s => 145s
* 422 tests: 131s => 30s
To see the difference in performance, see this flame graph comparison:
Before:
After:
Notice how many times `recreate_all` shows up in the "before" graph (it actually shows up more than once), …
> Truncate data on reset / re-use existing metadata instance

- setup.py
See [here](https://github.com/boto/botocore/commit/f2f12a23b7937397b34e41698c0ac2a3f0a951ba#diff-2eeaed663bd0d25b7e608891384b7298)
> drop python-dateutil<2.8.12 pin as upstream changes to boto-core now allow it

- .circleci/config.yml
- microcosm_postgres/createall.py
**Why?**
Services using `createall` may want to have custom behavior, depending on arguments that they will parse but that will be unrecognized here.
**What?**
Only parse know arguments in `createall`.
> Parse only known arguments in `createall`

- microcosm_postgres/operations.py
Usage is deprecated; users are expected to explicitly call reflect() on
the Metadata instance.
> Remove deprecated usage of `reflect` constructor param

- microcosm_postgres/encryption/models.py
- microcosm_postgres/tests/encryption/fixtures/sub_encryptable.py
- microcosm_postgres/tests/encryption/test_models.py
- microcosm_postgres/tests/factories/test_engine.py
This directive informs SQLA that it should restore the original context
(i.e. runid) for a for a given entity, instead of treating it as a
different context.
This prevents a warning from being erroneously emitted in the following
scenario:
* Unencrypted Parent class
* Encrypted polymorphic subclass of Parent
When the parent class is loaded, SQLA doesn't appear to take into
account any relationships of the relevant subclasses, meaning that it
needs to emit extra selects to fetch those attached entities once the
subclass has been fully loaded. Those additional queries then change
the context, causing SQLA to warn about it.
For more context:
https://github.com/zzzeek/sqlalchemy/commit/10b7937bb9994c365436af5e0c1931b2b07d12b1
https://github.com/sqlalchemy/sqlalchemy/issues/4094
> Explicitly enable `restore_load_context` for encrypted entities

- microcosm_postgres/encryption/encryptor.py
- microcosm_postgres/encryption/providers.py
- microcosm_postgres/encryption/registry.py
- microcosm_postgres/tests/encryption/test_encryptor.py
- microcosm_postgres/tests/encryption/test_models.py
- microcosm_postgres/tests/encryption/test_registry.py
Updates and replaces encryption to account for changes/deprecations relating to aws-encryption-sdk 2.1.x
The main driver change here appears to have been with "key commitment" (see ref).
The recommended change here is to use the client explicitly configured to be
backwards compatible.
This class was explicitly deprecated and removed in 2.x, to be replaced
with two different kinds of KeyProviders:
* StrictAwsKmsMasterKeyProvider
* DiscoveryAwsKmsMasterKeyProvider
The strict provider will continue to work as the previous provider had
done, encrypting new rows with the explicitly-provided keys.
Decryption, however, will use the discovery provider to decrypt values
in order to keep working with older accounts and values not explicitly
listed. This may change in the future, as it may be …
> Prepare library for aws-encryption-sdk 2.1.x migration

- .circleci/config.yml
Replaces the user/pass method with an auth token. This should fix issues
we've been seeing with 403s on release uploads.
> Update pypi upload method

- microcosm_postgres/tests/factories/test_engine.py
- microcosm_postgres/tests/temporary/test_temporary.py
- setup.py
- fix unit-test baseline - two were failing
- unpin aws-encryption-sdk and updated relevant code paths
*NOTE*: before making a release with these changes, services using this library (which are most of our stateful services) require a config update, see [this ansible-deploy PR](https://github.com/globality-corp/ansible-deploy/pull/3467) for example of required changes. we have yet to test these.
> Unpin aws-encryption-sdk

- setup.py
This is to ensure compatability with latest 1.4.x in preparation for sqlalchemy 2.x release and related bugfixes affecting microcosm-eventsource.
See also:
https://github.com/sqlalchemy/sqlalchemy/issues/6256
https://github.com/globality-corp/microcosm-eventsource/pull/74
https://github.com/globality-corp/microcosm-eventsource/pull/75
> bump minimum version requirements of sqlalchemy and sqlalchemy-utils

- .bumpversion.cfg
- setup.py
Mainly, SQLALchemy 1.4.x support.
- SQLAlchemy and SQLAlchemy-utils dependencies updated to latest to incorporate compatability with 1.4.x and a recent bugfix affecting microcosm-eventsource
> Release 2.2.0

- .bumpversion.cfg
- microcosm_postgres/factories/engine.py
- setup.py
Accepting [_pool_recycle_](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_recycle) and [_pool_pre_ping_](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.pool_recycle) SQLAlchemy pool configuration params.
> Accept pool recycle and pre-ping configuration parameters

- .bumpversion.cfg
- microcosm_postgres/encryption/v2/column.py
- microcosm_postgres/encryption/v2/encoders.py
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/encryption/v2/test_encoders.py
- microcosm_postgres/tests/encryption/v2/test_encryption.py
- setup.py
- explicitly declaring `_encrypted` `_unencrypted`, sqlalchemy prefers explicit column declaration. For the time being, we'll keep the abstraction at this level to avoid confusion
- Setting the single tenant `encryptor` at the request level, this makes it easier to manage the access based on request parameters
> Add encryption v2

- .bumpversion.cfg
- microcosm_postgres/encryption/encryptor.py
- microcosm_postgres/encryption/registry.py
- microcosm_postgres/encryption/v2/column.py
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/test_employee_store_with_encryption.py
- setup.py
This PR gives us the ability to perform exact match searches on encrypted fields. It's done through the use of beacons.
Beacons are hash that's deterministically calculated such that every input has only one output.
More about beacons can be found on the aws encryption sdk docs: https://docs.aws.amazon.com/database-encryption-sdk/latest/devguide/using-beacons.html
Now we use the `*_beacon` value inside the SQL used in the query against the database e.g:
```
SELECT test_encryption_employee.id AS test_encryption_employee_id, test_encryption_employee.name_encrypted AS test_encryption_employee_name_encrypted, test_encryption_employee.name AS test_encryption_employee_name, test_encryption_employee.name_beacon AS test_encryption_employee_name_beacon
FROM test_encryption_employee
WHERE …
```
> Adding beacon implementation to encryptor hybrid

- microcosm_postgres/encryption/v2/encoders.py
- microcosm_postgres/tests/encryption/v2/test_encryption.py
- setup.py
Encryption v2 `JSONEncoder` to store null values as SQL NULL instead of JSON encoding of 'null'.
> JSONEncoder - none as null

- microcosm_postgres/encryption/providers.py
- microcosm_postgres/encryption/registry.py
- microcosm_postgres/tests/encryption/test_registry.py
Add a custom, restricted KMS master key provider, that could operate without `kms:GenerateDataKey` permission, but with `kms:GenerateDataKeyWithoutPlaintext` + `kms:Decode` instead. The provider is disabled by default, can be enabled by setting a flag per context key.
> Custom, restricted KMS master key provider

- .bumpversion.cfg
- setup.py
Drop the lowest cryptography dependency version to v35.
> Relax cryptography version constraint

- .bumpversion.cfg
- microcosm_postgres/encryption/v2/column.py
- microcosm_postgres/encryption/v2/encoders.py
- microcosm_postgres/encryption/v2/utils.py
- microcosm_postgres/tests/encryption/v2/test_encoders.py
- microcosm_postgres/tests/encryption/v2/test_encryption.py
- microcosm_postgres/tests/encryption/v2/test_utils.py
- microcosm_postgres/tests/test_employee_store_with_encryption.py
- setup.py
* Adding util to help with overriding the `._members` method (useful for upserts where we iterate over the member attributes)
* Adding Encode/Decode exceptions
* Adding fix for auto filter fields (providing same interface as normal instrumented attributes)
From this:
```
def encode(self, value: list[T]) -> str:
>       return json.dumps([self.element_encoder.encode(element) for element in value])
E       TypeError: 'NoneType' object is not iterable
```
To this:
```
self = <microcosm_postgres.encryption.v2.encoders.ArrayEncoder object at 0x111830d60>, value = None
def wrapped(self, value):
try:
return func(self, value)
except Exception as e:
>           raise Encoder.EncodeException(f"Failed to encode value {value}") from e
E …
```
> Misc improvements

- microcosm_postgres/encryption/v2/encoders.py
- microcosm_postgres/tests/encryption/v2/test_encoders.py
- microcosm_postgres/tests/encryption/v2/test_encryption.py
This PR adds a `TextEncoder` for encryption. It acts like the existing `StringEncoder`, but for the `sqlalchemy.Text` type.
> feat: add a TextEncoder for encryption

- .bumpversion.cfg
- microcosm_postgres/encryption/v2/column.py
- microcosm_postgres/encryption/v2/encoders.py
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/test_employee_store_with_encryption.py
- setup.py
This enables matching beacons on array type columns e.g `ARRAY(String())`.
Example code:
```python
if skills is not None:
query = query.filter(
cast(Employee.skills, ARRAY(Text)).contains(
self._beaconise(skills, use_array=True) if self._check_if_using_encryption() else skills,
),
)
```
Note that it wasn't possible to hide more of this within the beacon comparator due to the usage of a postgresql Array type which has it's own `override` method. We have to use the postgresql array type as it comes with the helper `contains` which we use in the compiled sql at the database layer.
> Beaconised array matching

- .bumpversion.cfg
- microcosm_postgres/encryption/v2/encoders.py
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/test_employee_store_with_encryption.py
- setup.py
The implementation that was put together for beacons has a small bug which prevents empty arrays from being used:
```
microcosm_postgres.encryption.v2.encoders.Encoder.EncodeException: Error encoding value: Error encoding value: list index out of range
```
which is due to the `isinstance` check:
```
assert isinstance(raw[0], str)
```
> Fixing bug with empty array - array encoder - encryption v2

- .bumpversion.cfg
- microcosm_postgres/encryption/encryptor.py
- microcosm_postgres/encryption/registry.py
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/encryption/test_registry.py
- microcosm_postgres/tests/test_employee_store_with_encryption.py
- setup.py
updating default encryption creation such that it's only created if there are available account ids / key ids in config.
> Default encryptor not created if no account ids / key ids

- .bumpversion.cfg
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/encryption/v2/test_encryption.py
- setup.py
Fixing default decryptor to not interfere with column defaults; the encryptor should claim in _should encrypt_ only in case when the encryptor exists with non-null encrypting materials manager.
> Fix default decryptor with column defaults

- .bumpversion.cfg
- microcosm_postgres/encryption/encryptor.py
- microcosm_postgres/encryption/v2/beacons.py
- microcosm_postgres/encryption/v2/column.py
- microcosm_postgres/encryption/v2/encryptors.py
- microcosm_postgres/tests/encryption/v2/reencryption/test_cli.py
- microcosm_postgres/tests/test_employee_store_with_encryption.py
- setup.py
Adding ability to specify which hashing algorithm you'd like to use for the beacon generation.
This can be configured at the column level. 
Default is to use the plain SHA-256.
> Adding beacon hashing algorithm
