microcosm_postgres/types.py

Adds an enum column type that uses by-name (instead of by-value) semantics.

Add enum type.

---

microcosm_postgres/cloning.py
microcosm_postgres/context.py
microcosm_postgres/store.py
microcosm_postgres/tests/example.py
microcosm_postgres/tests/test_example.py

Why?
Often we know a unique result will be returned given a certain set of criteria but we need to do a full search and then get the first element of the returned array. There are also several custom implementations of these types of searches so creating a generic function.

Add the ability to do an exact search

---

microcosm_postgres/encryption/encryptor.py
microcosm_postgres/encryption/providers.py
microcosm_postgres/encryption/registry.py
microcosm_postgres/tests/encryption/test_encryptor.py
setup.py

Using a simple in app memory cache (`LocalCryptoMaterialsCache`) 
Enabled by a simple config
For more details: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/data-key-caching.html

Support data key caching for encryption

---

.bumpversion.cfg
microcosm_postgres/encryption/encryptor.py
microcosm_postgres/encryption/providers.py
microcosm_postgres/encryption/registry.py
microcosm_postgres/tests/encryption/test_encryptor.py
setup.py

Release https://github.com/globality-corp/microcosm-postgres/pull/62
Using a simple in app memory cache (LocalCryptoMaterialsCache)
Enabled by a simple config
For more details: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/data-key-caching.html

Release:  Support CachingCryptoMaterialsManager

---

.bumpversion.cfg
setup.py

Merge master to develop

---

.bumpversion.cfg
microcosm_postgres/encryption/models.py
microcosm_postgres/encryption/store.py
microcosm_postgres/tests/encryption/fixtures/encrpytable.py
microcosm_postgres/tests/encryption/fixtures/json_encrpytable.py
microcosm_postgres/tests/encryption/test_models.py
setup.py

Release: https://github.com/globality-corp/microcosm-postgres/pull/65

Encryption: delete and update

---

.bumpversion.cfg
microcosm_postgres/encryption/models.py
microcosm_postgres/encryption/store.py
microcosm_postgres/tests/encryption/fixtures/encryptable.py
microcosm_postgres/tests/encryption/fixtures/json_encryptable.py
microcosm_postgres/tests/encryption/fixtures/nullable_encryptable.py
microcosm_postgres/tests/encryption/test_models.py
setup.py

Release https://github.com/globality-corp/microcosm-postgres/pull/69
EncryptableStore.update is going to support seamlessly update
The controller won't have to

EncryptableStore.update

---

.bumpversion.cfg
microcosm_postgres/encryption/models.py
microcosm_postgres/encryption/store.py
microcosm_postgres/tests/encryption/test_models.py
setup.py

Why?
The separation between `on_load` and `decrypt_instance` was buggy. Fixed it and added a test

Fix encryption

---

microcosm_postgres/encryption/models.py
microcosm_postgres/temporary/factories.py
microcosm_postgres/temporary/methods.py
microcosm_postgres/tests/temporary/test_temporary.py

Having such a method was discussed in https://github.com/globality-corp/microcosm-postgres/pull/49/files#r204487697. We now have use cases for it.

Function for batch upsert with update on conflict

---

.bumpversion.cfg
.globality/build.json
microcosm_postgres/encryption/models.py
microcosm_postgres/temporary/factories.py
microcosm_postgres/temporary/methods.py
microcosm_postgres/tests/temporary/test_temporary.py
setup.py

Releases https://github.com/globality-corp/microcosm-postgres/pull/77

Release 1.17.0

---

.bumpversion.cfg
.github/CODEOWNERS
setup.py

Releases https://github.com/globality-corp/microcosm-postgres/pull/87

Release version 1.21.0

---

entrypoint.sh
setup.py

Deal with API conflict with new release of AWS encryption

Pin AWS Encryption Dependency

---

README.md

Accounts for needed configuration changes for encryption updates.

Add a 1.x => 2.x migration guide

---

.bumpversion.cfg
.circleci/config.yml
setup.py

Why?
See https://github.com/globality-corp/microcosm-flask/pull/330
Auth has been moved

Publish package using the correct context

---

.bumpversion.cfg
microcosm_postgres/factories/sessionmaker.py
microcosm_postgres/factories/shards.py
microcosm_postgres/migrate.py
microcosm_postgres/sharded_subgraph.py
microcosm_postgres/shards.py
setup.py

Automatically use horizontally sharded sessionmaker if configured (#121)

---

.bumpversion.cfg
microcosm_postgres/factories/shards.py
microcosm_postgres/tests/factories/test_shards.py
setup.py

Make the shard host and password required (#124)

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/encryption/v2/encryptors.py
microcosm_postgres/tests/encryption/v2/test_encoders.py
microcosm_postgres/tests/encryption/v2/test_encryption.py
setup.py

* Set the untouched column to null
* Set status code on EnryptorNotBound error
* Add tests for adding/removing encryption from row
* Add encoders for datetime

Bump version to 3.5.4

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/encryption/v2/encryptors.py
microcosm_postgres/tests/encryption/v2/test_encryption.py
setup.py

* Add new encryption_property that simplifies setup
* Set default based on should_encrypt

Add new encryption_property that simplifies setup (#134)

---

microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/tests/encryption/v2/test_encoders.py
microcosm_postgres/tests/encryption/v2/test_encryption.py

Add `EnumEncoder` that encodes and decodes an enum by its name.

Add EnumEncoder

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/tests/encryption/v2/test_encoders.py
setup.py

StringEncoder to stringify Any values.

Forgiving StringEncoder

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/temporary/methods.py
microcosm_postgres/tests/encryption/v2/test_encryption.py
setup.py

Transient table insert method to exclude encrypted columns.

Transient table support for encryption v2

---

.bumpversion.cfg
microcosm_postgres/encryption/encryptor.py
microcosm_postgres/encryption/providers.py
microcosm_postgres/encryption/registry.py
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/encryption/v2/encryptors.py
microcosm_postgres/encryption/v2/utils.py
microcosm_postgres/temporary/methods.py
microcosm_postgres/tests/encryption/test_registry.py
microcosm_postgres/tests/encryption/v2/test_encoders.py
microcosm_postgres/tests/encryption/v2/test_encryption.py
microcosm_postgres/tests/encryption/v2/test_utils.py
microcosm_postgres/tests/test_employee_store_with_encryption.py
setup.py

Includes:
* https://github.com/globality-corp/microcosm-postgres/pull/137
* https://github.com/globality-corp/microcosm-postgres/pull/138
* https://github.com/globality-corp/microcosm-postgres/pull/140
* https://github.com/globality-corp/microcosm-postgres/pull/139
* https://github.com/globality-corp/microcosm-postgres/pull/143
* https://github.com/globality-corp/microcosm-postgres/pull/144
* https://github.com/globality-corp/microcosm-postgres/pull/145

Sync v2 release branch with v3 changes

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/utils.py
microcosm_postgres/tests/encryption/v2/test_utils.py
microcosm_postgres/tests/test_employee_store_with_encryption.py
setup.py

This adds implementation and unit tests for:
* inserting (with and without encryption)
* upserting (with and without encryption)
* unique constraints (over encrypted / unencrypted columns)
* Support for encrypted and unencrypted contexts with and without beacon columns implemented

Allow for direct inserts with beacons + unit tests for unique constraints with encrypted / unencrypted data

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/utils.py
microcosm_postgres/tests/encryption/v2/test_utils.py
microcosm_postgres/tests/test_employee_store_with_encryption.py
setup.py

Syncing from master:
* https://github.com/globality-corp/microcosm-postgres/pull/146

Sync master with v2 branch

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/tests/encryption/v2/test_encoders.py
microcosm_postgres/tests/encryption/v2/test_encryption.py
setup.py

This PR syncs the following PR from master: https://github.com/globality-corp/microcosm-postgres/pull/147

Sync with master for TextEncoder

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/encryption/v2/encryptors.py
microcosm_postgres/tests/test_employee_store_with_encryption.py
setup.py

Syncing from master:
* https://github.com/globality-corp/microcosm-postgres/pull/149

Master sync to release 2.X

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/encoders.py
setup.py

Bumping to 2.9.0 as the previous version (2.8.2) was already taken

Bumping version - 2.9.0

---

.bumpversion.cfg
microcosm_postgres/encryption/providers.py
setup.py

Logging errors from restricted KMS master key provider.

Log restricted KMS provider errors

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/encoders.py
microcosm_postgres/encryption/v2/encryptors.py
microcosm_postgres/tests/test_employee_store_with_encryption.py
setup.py

Syncing from master:
* https://github.com/globality-corp/microcosm-postgres/pull/154

release-2 master sync

---

.bumpversion.cfg
microcosm_postgres/encryption/encryptor.py
microcosm_postgres/encryption/registry.py
microcosm_postgres/encryption/v2/encryptors.py
microcosm_postgres/tests/encryption/test_registry.py
microcosm_postgres/tests/encryption/v2/test_encryption.py
microcosm_postgres/tests/test_employee_store_with_encryption.py
setup.py

sync: https://github.com/globality-corp/microcosm-postgres/pull/158

Release 2 master sync v3

---

.bumpversion.cfg
microcosm_postgres/encryption/encryptor.py
microcosm_postgres/encryption/v2/column.py
microcosm_postgres/encryption/v2/encryptors.py
setup.py

Updating recent changes for python39 compatibility.

Python39 fixes

---

.bumpversion.cfg
microcosm_postgres/encryption/v2/contexts.py
microcosm_postgres/encryption/v2/reencryption/cli.py
microcosm_postgres/encryption/v2/reencryption/stats.py
microcosm_postgres/encryption/v2/reencryption/utils.py
microcosm_postgres/tests/encryption/v2/reencryption/test_cli.py
setup.py

Release 2 master sync
